### ISSUE TITLE
'Edistr' object has no attribute 'add_points'

### ISSUE THREAD

**Issue by markuspreston** [luca-fiorito-11/sandy#111]
Hi,

I'm trying to generate random samples from an ENDF file of U-235, running SANDY from the Linux command line. There seems to be an issue when sampling the outgoing-particle energy distributions, as I get the following error:

> edistr = sandy.Edistr.from_endf6(endfnew).add_points(extra_points)
AttributeError: 'Edistr' object has no attribute 'add_points'

It seems that there was an 'add_points' function in an earlier version of the Edistr class definition in pfns.py, but that this was removed at some point (perhaps replaced by add_energy_points, but the reference in sampling.py is not updated?).

/Markus

**Comment by luca-fiorito-11** [comment]
Hi @markuspreston ,

this is a know issue that at a moment we have to fix.
I suppose that you are using the git `develop` branch to create samples...can you confirm?

if that is the case, I suggest that you consult the [installation page](https://github.com/luca-fiorito-11/sandy/blob/develop/INSTALL.md#git-branches).
I quote:
> The development of SANDY is mostly carried out on the git branch develop. In this branch you should have the latest features available. We recommend using this branch if you want to use SANDY as an interface to nuclear data files. All SANDY tutorials available here were produced with the develop branch and might not work on other branches.
>
> The master branch was originally developed for creating random perturbed files of evaluated nuclear data libraries. If this is your objective, that is, you could't care less of how SANDY works and just want some results, then you should use the git branch master.  

With a `git checkout master` and again `python setup.py install` you should overcome this issue.
Also, if you don't care of sampling angular/energy distributions, I recommend calling sandy with option `--mf 33`.

Example
---------
`sandy   <your_file>  --mf 33  -S 100  -N 40`

or alternatively

`sandy   <your_file>   --errorr  --mf 33  -S 100  -N 40`

Let me know if it woks!

Luca

**Comment by markuspreston** [comment]
Thanks @luca-fiorito-11, now it works.
