### ISSUE TITLE
add njoy wrapper

### ISSUE THREAD

**Issue by luca-fiorito-11** [luca-fiorito-11/sandy#13]
Add `njoy` module at root level to produce predefined NJOY2016 inputs and to run the code.
The following function must be implemented:

- [x] produce ace files for fast evaluations
- [x] produce pendf files for fast evaluations
- [ ] produce ace files for thermal evaluations
- [ ] produce pendf files for thermal evaluations
- [x] produce ace files for proton evaluations
- [ ] produce ace files for photon evaluations

**Comment by luca-fiorito-11** [comment]
ace and pendf files for fast evaluations can be produced with NJOY2016 in branch `njoy`

**Comment by BorKos** [comment]
Luca, njoy wrapper functionality with ace outputs works perfect! Thanks!

**Comment by luca-fiorito-11** [comment]
No further capabilities for TSL and photon data are planned.
Then, I just close this!
