### ISSUE TITLE
Not in control format

### ISSUE THREAD

**Issue by AnderGray** [luca-fiorito-11/sandy#131]
With the newer endfb (and tendl) libraries I keep getting this error:

```
> sandy n-026_Fe_056.endf 

ERROR:  line ' $Rev:: 1518     $  $Date:: 2018-02-02#$                             1 0  0
' is not in CONTROL format
```

**Comment by luca-fiorito-11** [comment]
Can you just let us know what branch you are using?

**Comment by AnderGray** [comment]
I believe the master branch, I installed the following way:

```
    git clone https://github.com/luca-fiorito-11/sandy.git
    cd sandy

    python3 setup.py install --user
```

**Comment by luca-fiorito-11** [comment]
Just to be sure, can you type `git status` or `git branch` and make sure you are on `master`?
If you are not, you can switch to `master` following the [installation guide](https://github.com/luca-fiorito-11/sandy/blob/develop/INSTALL.md).

For reproducibility purposes, what version of the endf/b or tendl library are you working with?

**Comment by AnderGray** [comment]
Thanks for taking a look.

Yeah, I'm definitely on master. And I've been testing it out on endf/b viii. Attached is the file.

[n-026_Fe_056.txt](https://github.com/luca-fiorito-11/sandy/files/8091775/n-026_Fe_056.txt)

**Comment by luca-fiorito-11** [comment]
HI @AnderGray ,

I finally found the time to have a look at your problem.
SANDY raises an error as it doesn't recognize the file as being formatted according to the ENDF-6 format rules.

Quoting the [ENDF-6 manual](https://www.oecd-nea.org/dbdata/data/manual-endf/endf102.pdf) section 0.6.1:
> Finally, a section is divided into records. Every record on a tape contains three identification numbers: MAT,
> MF, and MT. These numbers are always in increasing numerical order, and the hierarchy is
> MAT, MF, MT. The end of a section, file, or material is signaled by special records called
> SEND, FEND, and MEND, respectively.

The file that you attached does not contain any SEND, FEND and MEND special records. These are basically 5 digits at the end of each file line that act as pointers to indicate how many lines of a given section are already parsed.
They are practically useless, and apparently ENDF/B-VIII.0 decided to remove them.

In the future we will try and make SANDY less strict regarding format compliancy (this is already implemented in the `develop` branch, although that branch is not stable enough to produce random samples).
For the moment I recommend that you add 5 digits at the end of each line. You can easily do it with sed, as

`sed "s/$/11111/" <YOUR_FILE >NEW_COPY`

**Comment by AnderGray** [comment]
Thanks for taking a look! This is very useful and has solved the problem
