### ISSUE TITLE
Extracting MF=31 (nubar) covariance with SANDY API

### ISSUE THREAD

**Issue by nicoloabrate** [luca-fiorito-11/sandy#221]
Dear Sandy developers,
I am currently using SANDY as an API to generate the ERRORR files for different applications (e.g., singular value decomposition, sandwhich rule calculations using the sensitivity coeffs. computed by other codes, and so on). So far, I was able to generate the ERRORR files for the MF=32,33 and the related MT using some lines of code as follows,

`
endf = sandy.get_endf6_file(the_library_i_want, "xs", za)`
`pendf = endf.get_pendf(temperature=temperature)`
`myerrorr = endf.get_errorr(njoy=os.environ['NJOY'], pendf=pendf,
                                   temperature=temperature, ign=1,ek=group_structure)`

Now I am interested in doing the same thing but for the nubar covariance (MF=31). How can I do that? Looking at the `sandy.njoy.process` method and sub-methods I do not actually see how to specify the `mfcov` option of the `card 7` in the NJOY deck (which allows to choose among MF 31,32,33,...).

Could you please help me?
Thank you so much
Nicolo'

**Comment by luca-fiorito-11** [comment]
Hi @nicoloabrate,
@EnricaBelfiore will have a look asap.
Cheers,
Luca
