### ISSUE TITLE
Handle e+0 Case in write_float Function

### ISSUE THREAD

**Issue by janmalec** [luca-fiorito-11/sandy#307]
The write_float function handles the e-0 case but does not address the e+0 case, leading to inconsistent formatting in scientific notation. This inconsistency results in improperly formatted ENDF files, causing processing to fail. The function should be updated to replace both e-0 with - and e+0 with + to ensure proper formatting and successful processing.

Example where the old behavior fails:
`sandy.write_float(1-1e-8)`

**Comment by luca-fiorito-11** [comment]
see #306

**Comment by luca-fiorito-11** [comment]
closed with #308
