### ISSUE TITLE
ACE file generation

### ISSUE THREAD

**Issue by promojar** [luca-fiorito-11/sandy#43]
ACE files are not correctly generated when using SANDY to sample ENDF files and afterwards automatically process the perturbed files with NJOY. Only the ACE and xsdir for the last perturbed file are generated, even though NJOY runs for each perturbed file, probably because each time, the perturbed file is written with the identifier of the number of samples instead of the identifier number of the perturbed file, so they get overwritten continuously.

**Comment by luca-fiorito-11** [comment]
This is a bug associated to the `master`. Since most of the development is ongoing in the `develop` branch it can be that it takes a while before I can fix this.
But I'll try and have a look at it, anyway.
